"""add project_grade

Revision ID: 490c03ecd47c
Revises: 
Create Date: 2025-04-20 23:28:39.751405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '490c03ecd47c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supervisors', 'student_project_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supervisors', sa.Column('student_project_list', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
